### ISSUE TITLE
0.3.6 Regressions

### ISSUE THREAD

**Issue by iczman** [trptcolin/consistency_fail#47]
Upgrading to 0.3.6 produced following regressions:

```ruby
class OptionType < ApplicationRecord
  enum selection_rule: [:required_single, :optional_single, :optional_multiple]
end
```

```console
$ consistency_fail
Traceback (most recent call last):
	26: from /Users/<snipped>/.rbenv/versions/2.5.1/bin/consistency_fail:23:in `<main>'
	25: from /Users/<snipped>/.rbenv/versions/2.5.1/bin/consistency_fail:23:in `load'
	24: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/bin/consistency_fail:20:in `<top (required)>'
	23: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail.rb:11:in `run'
	22: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail/models.rb:19:in `preload_all'
	21: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail/models.rb:19:in `each'
	20: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail/models.rb:21:in `block in preload_all'
	19: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail/models.rb:21:in `each'
	18: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail/models.rb:22:in `block (2 levels) in preload_all'
	17: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	16: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	15: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	14: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	13: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	12: from /Users/<snipped>/<snipped>/app/models/option_type.rb:17:in `<main>'
	11: from /Users/<snipped>/<snipped>/app/models/option_type.rb:28:in `<class:OptionType>'
	10: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/enum.rb:155:in `enum'
	 9: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/enum.rb:155:in `each'
	 8: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/enum.rb:173:in `block in enum'
	 7: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/enum.rb:173:in `module_eval'
	 6: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/enum.rb:175:in `block (2 levels) in enum'
	 5: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/enum.rb:175:in `each'
	 4: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/enum.rb:175:in `each_with_index'
	 3: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/enum.rb:175:in `each'
	 2: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/enum.rb:192:in `block (3 levels) in enum'
	 1: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/enum.rb:229:in `detect_enum_conflict!'
/Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/enum.rb:234:in `raise_conflict_error': You tried to define an enum named "selection_rule" on the model "OptionType", but this will generate a instance method "required_single?", which is already defined by another enum. (ArgumentError)
```

Now with the enum removed:

```ruby
class OptionType < ApplicationRecord
end
```

```console
$ consistency_fail
Traceback (most recent call last):
	16: from /Users/<snipped>/.rbenv/versions/2.5.1/bin/consistency_fail:23:in `<main>'
	15: from /Users/<snipped>/.rbenv/versions/2.5.1/bin/consistency_fail:23:in `load'
	14: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/bin/consistency_fail:20:in `<top (required)>'
	13: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail.rb:11:in `run'
	12: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail/models.rb:19:in `preload_all'
	11: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail/models.rb:19:in `each'
	10: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail/models.rb:21:in `block in preload_all'
	 9: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail/models.rb:21:in `each'
	 8: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/consistency_fail-0.3.6/lib/consistency_fail/models.rb:22:in `block (2 levels) in preload_all'
	 7: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	 6: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	 5: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	 4: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	 3: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 2: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activestorage-5.2.1/app/models/active_storage/blob/representable.rb:3:in `<main>'
	 1: from /Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activestorage-5.2.1/app/models/active_storage/blob/representable.rb:6:in `<module:Representable>'
/Users/<snipped>/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/concern.rb:128:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
```

0.3.5 ran fine with above scenarios.

**Comment by trptcolin** [comment]
Yikes, thanks for reporting. I could reproduce with a new Rails app. Need to close that loop in the test suite here - currently we're only testing against ActiveRecord directly, not generating a Rails app, but we clearly should.

Just pushed 0.3.7 which reinstates the previous `require_dependency` behavior - my repro case works; can you confirm that this works for you?

**Comment by alphabt** [comment]
Yup 0.3.7 works now, thanks for the quick fix!

**Comment by trptcolin** [comment]
Great - thanks and sorry for the trouble!
